apps/employee/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('employee.views',
    url(r'^$', 'index', name='employee_index'),
    url(r'^office/$', 'office_index', name='office_index'),
)

apps/issue/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('issue.views',
    url(r'^$', 'index', name='issue_index'),
)

apps/project/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('project.views',
    url(r'^$', 'index', name='project_index'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^issue/', include('issue.urls')),
    url(r'^employee/', include('employee.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

apps/employee/models.py
from django.db import models
from django.contrib.auth.models import User

class Office(models.Model):
    name = models.CharField(max_length=255)
    address = models.TextField()
    phone = models.CharField(max_length=20)
    
class Employee(User):
    EMP = (
        ("pm","Project Manager"),
        ("n","NOC"),
        ("p","Programer"),
    )
    
    position = models.CharField(max_length=2,choices=EMP)
    office = models.ForeignKey(Office)
    phone = models.CharField(max_length=20)

apps/issue/models.py
from django.db import models

# Create your models here.

apps/project/models.py
from django.db import models

# Create your models here.

apps/employee/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from employee.models import Employee,Office

def index(request):
    return render_to_response("employee/index.html",{
            "employees" : Employee.objects.all() 
        },context_instance=RequestContext(request))

def office_index(request):
    return render_to_response("employee/office_index.html",{
            "offices" : Office.objects.all() 
        },context_instance=RequestContext(request))

apps/issue/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def index(request):
    return render_to_response("issue/index.html",{
        
        },context_instance=RequestContext(request))

apps/project/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def index(request):
    return render_to_response("project/index.html",{
        
        },context_instance=RequestContext(request))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
		<title>Network Service Center -- {% block title %}{%endblock%}</title>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />


		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap-responsive.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/imperio.css" />
        
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
	</head>
    <body>
        <div class="container-fluid nopadding">
            <div class="row-fluid">
                <div class="span12">
                    <div id="header">
                        <a href="#">
							<img src="/static/img/logo.png" alt="" />
						</a>
						<div class="hright">
							<div id="search" class="column">
								<div class="search">
									<form method="post" action="#">
										<input type="text" placeholder="Search here" value="Search here" name="keyword" id="keyword" /> 
									</form>
								</div>
							</div>
							<div id="userinfo" class="column">
								<a class="userinfo dropown-toggle" data-toggle="dropdown" href="#userinfo">
									<img alt="" src="img/avatar.jpg" />
									<span><strong>Admin</strong></span>
								</a>
                                    <ul class="dropdown-menu">
										<li><a href="#">Edit Profile</a></li>
										<li><a href="#">Edit Preferences</a></li>
										<li><a href="#">Private Messages</a></li>
										<li class="divider"></li>
										<li><a href="login.html">Logout</a></li>
									</ul>
							</div>
						</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid" id="container">
        <div class="row-fluid">
                <div class="span3 leftmenu">
                    <ul class="nav">
                        <li class="{% ifequal request.path "/issue/" %}active{% endifequal %}"><a href="{% url issue_index %}"><span class="ico"><i class="icon-home"></i></span><span class="text">Issue</span></a></li>
                        <li class="{% ifequal request.path "/project/" %}active{% endifequal %}"><a href="{% url project_index %}"><span class="ico"><i class="icon-edit"></i></span><span class="text">Project</span></a></li>
                        <li class="{% ifequal request.path "/employee/" %}active{% endifequal %}"><a href="{% url employee_index %}"><span class="ico"><i class="icon-bold"></i></span><span class="text">Employee</span></a></li>
                    </ul>
                </div>
            {% block container %}{% endblock %}
        </div>  
    
    
        <script type="text/javascript" src="/static/js/jquery.min.js"></script>
        <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
        <!-- Explorer canvas, for IE6-8 support of canvas elements -->
        <!--[if lt IE 9]>
            <script src="/static/js/excanvas.min.js"></script>
        <![endif]-->
        <script type="text/javascript" src="/static/js/imperio.general.js"></script>
	<script type="text/javascript" src="/static/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="/static/js/imperio.tables.js"></script>
    </body>

<!-- Mirrored from wbpreview.com/previews/WB0N98JX2/index.html by HTTrack Website Copier/3.x [XR&CO'2010], Tue, 04 Dec 2012 02:58:16 GMT -->
</html>

templates/employee/office_index.html
{% extends "base.html" %}
{% block container %}
<div class="span9" id="content">
    <div class="row-fluid quick-actions">
                        
        <div class="span2">
            <a class="quick-action" href="#">
                <span class="icon users"></span>
                Add Employee
            </a>
        </div>
       <div class="span2">
            <a class="quick-action" href="#">
                <span class="icon inbox"></span>
                Office List
            </a>
        </div>
       <div class="span2">
            <a class="quick-action" href="#">
                <span class="icon users"></span>
                Add Office
            </a>
        </div>
                    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="box">
                <div class="box-title">
                    Employee list
                </div>
                <div class="box-content nopadding">
                    <table id="datatable" class="table table-striped table-bordered">
                        <thead>
                                <tr>
                                        <th>Full Name</th>
                                        <th>Address</th>
                                        <th>Phone</th>
                                        <th>Position</th>
                                        <th>Phone</th>
                                </tr>
                        </thead>
                        <tbody>
                            {% for data in offices %}
                                <tr class="odd gradeX">
                                        <td>{{ data.name }}</td>
                                        <td>{{ data.address }}</td>
                                        <td>{{ data.phone }}</td>
                                        <td class="center">{{ data.get_position_display }}</td>
                                        <td class="center">{{ data.phone }}</td>
                                </tr>
                            {% endfor %}    
                        </tbody>
                        <tfoot>
                                <tr>
                                        <th>Rendering engine</th>
                                        <th>Browser</th>
                                        <th>Platform(s)</th>
                                        <th>Engine version</th>
                                        <th>CSS grade</th>
                                </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/issue/index.html
{% extends "base.html" %}

{% block title %} Issue Management{% endblock %}
{% block container %}
                <div class="span9" id="content">
                    <div class="row-fluid quick-actions">
                        <div class="span2">
                            <a href="#" class="quick-action">
                                <span class="icon users"></span>
                                Users
                            </a>
                        </div>
                        <div class="span2">
                            <a href="#" class="quick-action">
                                <span class="icon file"></span>
                                Blog Entries
                            </a>
                        </div>
                        <div class="span2">
                            <a href="#" class="quick-action">
                                <span class="icon conversation"></span>
                                Comments
                            </a>
                        </div>
                        <div class="span2">
                            <a href="#" class="quick-action">
                                <span class="icon picture"></span>
                                Images
                            </a>
                        </div>
                        <div class="span2">
                            <a href="#" class="quick-action">
                                <span class="icon pie_chart"></span>
                                Stats
                            </a>
                        </div>
                        <div class="span2">
                            <a href="#" class="quick-action">
                                <span class="icon shield"></span>
                                Security
                            </a>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span7">
                            <div class="box">
                                <div class="box-title">
                                    Example chart
                                </div>
                                <div class="box-content">
                                    <div id="chart" style="height: 220px;"></div>
                                </div>
                            </div>
                        </div>
                        <div class="span5">
                            <div class="box alternate">
                                <div class="box-title">
                                    <span class="ico"><i class="icon-repeat"></i></span>Recent Activity
                                </div>
                                <div class="box-content nopadding">
                                    <ul class="activity-list">
                                        <li><a href="#">
                                            <i class="icon-user"></i>
                                            <strong>Admin</strong> added <strong>1 user</strong> <span>2 hours ago</span>
                                        </a></li>
                                        <li><a href="#">
                                            <i class="icon-file"></i>
                                            <strong>Caroline Trin</strong> write a <strong>blog post</strong> <span>Yesterday</span>
                                        </a></li>
                                        <li><a href="#">
                                            <i class="icon-envelope"></i>
                                            <strong>John Doe</strong> sent a <strong>message</strong> <span>2 days ago</span>
                                        </a></li>
                                        <li><a href="#">
                                            <i class="icon-picture"></i>
                                            <strong>Matt Armon</strong> updated <strong>profile photo</strong> <span>2 days ago</span>
                                        </a></li>
                                        <li><a href="#">
                                            <i class="icon-user"></i>
                                            <strong>Admin</strong> bans <strong>3 users</strong> <span>week ago</span>
                                        </a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="box">
                                <div class="box-title">
                                    Table
                                </div>
                                <div class="box-content nopadding">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>First Name</th>
                                                <th>Last Name</th>
                                                <th>Username</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Caroline</td>
                                                <td>Trin</td>
                                                <td>@Carolint</td>
                                            </tr>
                                            <tr>
                                                <td>John</td>
                                                <td>Doe</td>
                                                <td>@jdoe</td>
                                            </tr>
                                            <tr>
                                                <td>Matt</td>
                                                <td>Armon</td>
                                                <td>@marmon</td>
                                            </tr>
                                            <tr>
                                                <td>Jane</td>
                                                <td>Kowalsky</td>
                                                <td>@jane-kow</td>
                                            </tr>
                                            <tr>
                                                <td>Tim</td>
                                                <td>Pacey</td>
                                                <td>@t-pac</td>
                                            </tr>
                                            <tr>
                                                <td>Steve</td>
                                                <td>Rovinsky</td>
                                                <td>@steve-sky</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="box">
                                <div class="box-title">
                                    Content
                                </div>
                                <div class="box-content">
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    </p>
                                    <p>
                                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                                    </p>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                                    </p>
                                </div>
                            </div>                        
                        </div>                    
                    </div>
                </div>
{% endblock %}

templates/project/index.html
{% extends "base.html" %}
{% block container %}
<div class="span9" id="content">
                   
    <div class="row-fluid">
        <div class="span12">
            <div class="box">
                <div class="box-title">
                    Employee list
                </div>
                <div class="box-content nopadding">
                    <table id="datatable" class="table table-striped table-bordered">
                        <thead>
                                <tr>
                                        <th>Full Name</th>
                                        <th>Username</th>
                                        <th>Email</th>
                                        <th>as</th>
                                        <th>CSS grade</th>
                                </tr>
                        </thead>
                        <tbody>
                            {% for data in users %}
                                <tr class="odd gradeX">
                                        <td>{{ data.get_full_name }}</td>
                                        <td>{{ data.username }}</td>
                                        <td>{{ data.email }}</td>
                                        <td class="center"> 4</td>
                                        <td class="center">X</td>
                                </tr>
                            {% endfor %}    
                        </tbody>
                        <tfoot>
                                <tr>
                                        <th>Rendering engine</th>
                                        <th>Browser</th>
                                        <th>Platform(s)</th>
                                        <th>Engine version</th>
                                        <th>CSS grade</th>
                                </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}